version: "3.8"

services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123123"
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d 
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: .
    container_name: go_app
    depends_on:
      - db
    volumes:
      - ./.config.toml:/app/.config.toml
    ports:
      - "8080:8080"
    restart: always
    command: ["./main"]
    networks:
      - app-network

volumes:
  db_data:
  
networks:
  app-network:
    driver: bridge